In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load the data
df = pd.read_csv("data.csv", header = None)
df

0    1    2    3    4    5    6    7    8    9    ...  91   92   93   \
0      0    0    0    0    0    0    0    0    0    0  ...   10    5    0   
1      0    0    0    0    0    0    0    0    0    0  ...    8    0    0   
2      0    0    0    0    0    0    0    0    0    0  ...   11    4    0   
3      0    0    0    0    0    0    0    0    0    0  ...    7    5    0   
4      0    0    4    0    0    0    0    0    0    0  ...   12    5    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
395    0    0    0    0    0    5    0    0    0    0  ...    0    0    0   
396    0    0    0    0    7    0    0    0    0    0  ...    0    0    0   
397    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
398    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
399    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

     94   95   96   97   98   99   100  
0      0    0    0    0    0    0    1  
1      0    0    0    0    0    0    1  
2      0    4    0    0    0    0    1  
3      0    0    0    0    0    0    1  
4      0    0    0    0    0    0    1  
..   ...  ...  ...  ...  ...  ...  ...  
395    0    0    0    0    0    0    4  
396    0    0    0    0    0    0    4  
397    0    0    0    0    0    0    4  
398    0    0    0    0    0    0    4  
399    0    4    0    0    0    0    4  

[400 rows x 101 columns]

In [111]:
# Get the last column as the true clusters 
true_cluster = df[df.columns[-1]]
T = df.iloc[:,:-1]

In [139]:
n_d = T.shape[0]
n_w = T.shape[1]
n_c = 4

In [140]:
# Initialize parameters
def initialize_random_params():
    gamma = np.ones((n_d, n_c)) / n_c 
    mu = np.random.normal(0, 1, size=(n_w, n_c))
    pi = gamma.sum(axis=0) / n_d
    
    return gamma, mu, pi

In [143]:
gamma

array([[ 1.00000000e+00,  1.73757803e+03, -1.21696635e-11,
         6.16807760e-09],
       [ 1.00000000e+00,  1.04752669e-07,  3.87108136e-06,
        -4.97303066e-01],
       [ 1.00000000e+00,  3.03891433e+14, -7.59506634e-12,
         3.41935764e+06],
       ...,
       [ 1.00000000e+00, -5.42628536e-03,  1.06926495e+04,
         2.12669982e+04],
       [ 1.00000000e+00,  6.11275107e+00,  1.55005496e+06,
         4.93605696e+08],
       [ 1.00000000e+00,  8.32155167e+01, -1.61886498e+00,
         1.10458234e+05]])

In [141]:
gamma, mu, pi = initialize_random_params()

In [142]:
# Test (please skip it)
gamma = np.zeros((n_d, n_c))
for i in range(n_d):
    for c in range(n_c):
        nom = 1
        denom = 0
        temp=1
        print("we currently in gamma {}, {}".format(i, c))
        for j in range(n_w):
            #print("the current mu is {}, the current T is {}".format(mu[j][c], T[i][j]))
            nom *= np.power(mu[j][c],T[j][i])
        nom *= pi[c] 
        #print("The nom is",nom)
        for sc in range(n_c):
            for j in range(n_w):
                temp *= np.power(mu[j][sc],T[j][i])
            denom += (pi[sc] * temp)
            #print("pi",pi[sc])
        #print("The denom is", denom)
        #print(nom/denom)
        gamma[i][c] = nom / denom

we currently in gamma 0, 0
we currently in gamma 0, 1
we currently in gamma 0, 2
we currently in gamma 0, 3
we currently in gamma 1, 0
we currently in gamma 1, 1
we currently in gamma 1, 2
we currently in gamma 1, 3
we currently in gamma 2, 0
we currently in gamma 2, 1
we currently in gamma 2, 2
we currently in gamma 2, 3
we currently in gamma 3, 0
we currently in gamma 3, 1
we currently in gamma 3, 2
we currently in gamma 3, 3
we currently in gamma 4, 0
we currently in gamma 4, 1
we currently in gamma 4, 2
we currently in gamma 4, 3
we currently in gamma 5, 0
we currently in gamma 5, 1
we currently in gamma 5, 2
we currently in gamma 5, 3
we currently in gamma 6, 0
we currently in gamma 6, 1
we currently in gamma 6, 2
we currently in gamma 6, 3
we currently in gamma 7, 0
we currently in gamma 7, 1
we currently in gamma 7, 2
we currently in gamma 7, 3
we currently in gamma 8, 0
we currently in gamma 8, 1
we currently in gamma 8, 2
we currently in gamma 8, 3
we currently in gamma 9, 0
w

we currently in gamma 74, 1
we currently in gamma 74, 2
we currently in gamma 74, 3
we currently in gamma 75, 0
we currently in gamma 75, 1
we currently in gamma 75, 2
we currently in gamma 75, 3
we currently in gamma 76, 0
we currently in gamma 76, 1
we currently in gamma 76, 2
we currently in gamma 76, 3
we currently in gamma 77, 0
we currently in gamma 77, 1
we currently in gamma 77, 2
we currently in gamma 77, 3
we currently in gamma 78, 0
we currently in gamma 78, 1
we currently in gamma 78, 2
we currently in gamma 78, 3
we currently in gamma 79, 0
we currently in gamma 79, 1
we currently in gamma 79, 2
we currently in gamma 79, 3
we currently in gamma 80, 0
we currently in gamma 80, 1
we currently in gamma 80, 2
we currently in gamma 80, 3
we currently in gamma 81, 0
we currently in gamma 81, 1
we currently in gamma 81, 2
we currently in gamma 81, 3
we currently in gamma 82, 0
we currently in gamma 82, 1
we currently in gamma 82, 2
we currently in gamma 82, 3
we currently in gamm

we currently in gamma 146, 1
we currently in gamma 146, 2
we currently in gamma 146, 3
we currently in gamma 147, 0
we currently in gamma 147, 1
we currently in gamma 147, 2
we currently in gamma 147, 3
we currently in gamma 148, 0
we currently in gamma 148, 1
we currently in gamma 148, 2
we currently in gamma 148, 3
we currently in gamma 149, 0
we currently in gamma 149, 1
we currently in gamma 149, 2
we currently in gamma 149, 3
we currently in gamma 150, 0
we currently in gamma 150, 1
we currently in gamma 150, 2
we currently in gamma 150, 3
we currently in gamma 151, 0
we currently in gamma 151, 1
we currently in gamma 151, 2
we currently in gamma 151, 3
we currently in gamma 152, 0
we currently in gamma 152, 1
we currently in gamma 152, 2
we currently in gamma 152, 3
we currently in gamma 153, 0
we currently in gamma 153, 1
we currently in gamma 153, 2
we currently in gamma 153, 3
we currently in gamma 154, 0
we currently in gamma 154, 1
we currently in gamma 154, 2
we currently i

we currently in gamma 219, 2
we currently in gamma 219, 3
we currently in gamma 220, 0
we currently in gamma 220, 1
we currently in gamma 220, 2
we currently in gamma 220, 3
we currently in gamma 221, 0
we currently in gamma 221, 1
we currently in gamma 221, 2
we currently in gamma 221, 3
we currently in gamma 222, 0
we currently in gamma 222, 1
we currently in gamma 222, 2
we currently in gamma 222, 3
we currently in gamma 223, 0
we currently in gamma 223, 1
we currently in gamma 223, 2
we currently in gamma 223, 3
we currently in gamma 224, 0
we currently in gamma 224, 1
we currently in gamma 224, 2
we currently in gamma 224, 3
we currently in gamma 225, 0
we currently in gamma 225, 1
we currently in gamma 225, 2
we currently in gamma 225, 3
we currently in gamma 226, 0
we currently in gamma 226, 1
we currently in gamma 226, 2
we currently in gamma 226, 3
we currently in gamma 227, 0
we currently in gamma 227, 1
we currently in gamma 227, 2
we currently in gamma 227, 3
we currently i

we currently in gamma 292, 2
we currently in gamma 292, 3
we currently in gamma 293, 0
we currently in gamma 293, 1
we currently in gamma 293, 2
we currently in gamma 293, 3
we currently in gamma 294, 0
we currently in gamma 294, 1
we currently in gamma 294, 2
we currently in gamma 294, 3
we currently in gamma 295, 0
we currently in gamma 295, 1
we currently in gamma 295, 2
we currently in gamma 295, 3
we currently in gamma 296, 0
we currently in gamma 296, 1
we currently in gamma 296, 2
we currently in gamma 296, 3
we currently in gamma 297, 0
we currently in gamma 297, 1
we currently in gamma 297, 2
we currently in gamma 297, 3
we currently in gamma 298, 0
we currently in gamma 298, 1
we currently in gamma 298, 2
we currently in gamma 298, 3
we currently in gamma 299, 0
we currently in gamma 299, 1
we currently in gamma 299, 2
we currently in gamma 299, 3
we currently in gamma 300, 0
we currently in gamma 300, 1
we currently in gamma 300, 2
we currently in gamma 300, 3
we currently i

we currently in gamma 368, 3
we currently in gamma 369, 0
we currently in gamma 369, 1
we currently in gamma 369, 2
we currently in gamma 369, 3
we currently in gamma 370, 0
we currently in gamma 370, 1
we currently in gamma 370, 2
we currently in gamma 370, 3
we currently in gamma 371, 0
we currently in gamma 371, 1
we currently in gamma 371, 2
we currently in gamma 371, 3
we currently in gamma 372, 0
we currently in gamma 372, 1
we currently in gamma 372, 2
we currently in gamma 372, 3
we currently in gamma 373, 0
we currently in gamma 373, 1
we currently in gamma 373, 2
we currently in gamma 373, 3
we currently in gamma 374, 0
we currently in gamma 374, 1
we currently in gamma 374, 2
we currently in gamma 374, 3
we currently in gamma 375, 0
we currently in gamma 375, 1
we currently in gamma 375, 2
we currently in gamma 375, 3
we currently in gamma 376, 0
we currently in gamma 376, 1
we currently in gamma 376, 2
we currently in gamma 376, 3
we currently in gamma 377, 0
we currently i

In [129]:
def update_gamma(T, mu, pi):
    gamma = np.zeros((n_d, n_c))
    for i in range(n_d):
        for c in range(n_c):
            nom = 1
            denom = 0
            temp=1
            for j in range(n_w):
                nom *= np.power(mu[j][c],T[j][i])
            nom *= pi[c] 
            for sc in range(n_c):
                for j in range(n_w):
                    temp *= np.power(mu[j][sc],T[j][i])
                denom += (pi[sc] * temp)
            gamma[i][c] = nom / denom
    return gamma

def update_mu(T, gamma):
    mu = np.zeros((n_w, n_c))   
    nom = np.dot(T.T, gamma)
    denom = np.zeros((1,4))
    for j in range(n_w):
        denom += nom[j]
    mu = nom/denom
    
    return mu

def update_pi(gamma):
    pi = gamma.sum(axis=0) / n_d
    return pi

In [130]:
# E step 
def e_step(T, mu, pi):
    return update_gamma(T, mu, pi)

# M step
def m_step(T, gamma):
    return update_mu(T, gamma), update_pi(gamma)

#def compute_ll(T, gamma, mu, pi):
#    ll = 
#    return np.mean(loglikelihood)

In [135]:
# Run em
max_iter = 30
count = 0
pred = np.zeros(n_d)
gamma, mu, pi = initialize_random_params()
while(count < max_iter):
    print(count)
    # Run e_step and m_step, update the params
    gamma = e_step(T, mu, pi)
    print(gamma)
    mu, pi = m_step(T, gamma)
    # Get the prediction of the cluster as the index of the max probability
    for i in range(len(gamma)): # row_i = 1 * 4
        row_i = list(gamma[i])
        pred[i] = row_i.index(max(row_i))+1
    count+=1

0
[[ 9.99999552e-01 -2.14105941e+06 -1.52742267e+21  4.06820784e+00]
 [ 9.98999653e-01 -5.25992318e+05 -3.89055480e+20  4.24566919e+01]
 [ 1.00000086e+00  1.26151817e+04 -2.58773647e+19 -1.06288799e+01]
 ...
 [ 1.00000000e+00  2.59160228e-01 -1.18556753e+04  1.71989211e+11]
 [ 1.00000000e+00  2.41011443e+02  5.41044470e+00  1.32559757e+06]
 [ 1.00000000e+00 -1.34175178e-01 -6.69398744e-03 -4.77797993e+08]]
1
[[ 1.00000000e+000 -1.14685256e-152  4.21810653e-060  0.00000000e+000]
 [ 1.00000000e+000  2.01500692e-088  1.14045380e-027  0.00000000e+000]
 [ 1.00000000e+000  1.67944502e-048  4.41709280e-018  0.00000000e+000]
 ...
 [ 1.00000000e+000  0.00000000e+000 -0.00000000e+000  5.15762848e-081]
 [ 1.00000000e+000  0.00000000e+000 -0.00000000e+000  2.32083094e-041]
 [ 1.00000000e+000 -0.00000000e+000 -0.00000000e+000 -0.00000000e+000]]
2


KeyboardInterrupt: 

In [132]:
pred

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [133]:
# Report accuracy
count = 0
for i in range(len(true_cluster)):
    if true_cluster[i] == pred[i]:
        count+=1
        
accuracy = count/400
print(accuracy)

0.25
